"""
Django settings for data_science_portal_api project.

Generated by 'django-admin startproject' using Django 2.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if 'DJANGO_DEBUG' in os.environ and os.environ['DJANGO_DEBUG'] in ['False', 'FALSE', 'F'] else True


# The allowed host whi ch behavior as the web server
ALLOWED_HOSTS = [ 'localhost', '127.0.0.1', 'findex-ds-portal-api-test.azurewebsites.net', 'findex-ds-portal-api.azurewebsites.net', '10.3.90.204' ]
if 'DJANGO_ALLOWED_HOST' in os.environ:
    ALLOWED_HOSTS.append( os.environ['DJANGO_ALLOWED_HOST'] )


# AZURE B2C
TENANT_NAME=os.environ['B2C_TENANT_NAME']
POLICY_NAME=os.environ['B2C_POLICY_NAME']
APP_ID = [ os.environ['B2C_APP_ID'] ]
RETURN_URL = os.environ['B2C_REPLY_URL']

#POWER BI
PBI_AUTHENTICATION_MODE = os.environ.get('PBI_AUTHENTICATION_MODE','')
PBI_CLIENT_ID = os.environ.get('PBI_CLIENT_ID','')
PBI_CLIENT_SECRET = os.environ.get('PBI_CLIENT_SECRET','')
PBI_AUTHORITY_URL = os.environ.get('PBI_AUTHORITY_URL','') + os.environ.get('PBI_TENANT_ID','')
PBI_MASTER_USER = os.environ.get('PBI_MASTER_USER','')
PBI_MASTER_PASS = os.environ.get('PBI_MASTER_PASS','')
PBI_SCOPE = [os.environ.get('PBI_SCOPE','')]

#Storage Account
ENVIRONMENT     = os.environ.get('DOWNLOAD_ENVIRONMENT', '')
STORAGE_ACCOUNT = os.environ.get('DOWNLOAD_STORAGE_ACCOUNT','')
STORAGE_KEY     = os.environ.get('DOWNLOAD_STORAGE_KEY','')
USERMAIL_TABLE  = os.environ.get('INVITE_USERMAIL_T ABLE','')
DOWNLOAD_TABLE  = os.environ.get('DOWNLOAD_LOG_TABLE','')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'graphene_django',
    'corsheaders',                               ## ALERT!!  CORS!!!
    'access_control'
]

MIDDLEWARE = [
    'corsheaders.middleware .CorsMiddleware',    ## ALERT!!  CORS!!!
    'django.middleware.common.CommonMiddleware',

    'django.middlewar e.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'access_control.custom_httprequests.HttpPostTunnelingMiddleware',
]

CORS_ORIGIN_ALLOW_ALL=True                      ## ALERT!!  CORS!!!

ROOT_URLCONF = 'data_science_portal_api.urls'

TEMPLATES = [
    {
        'BACKEND ': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'data_science_portal_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ['DEFAULT_DBENGINE'],
        'NAME': os.environ['DEFAULT_DBNAME'],
        'USER': os.environ['DEFAULT_DBUSER'],
        'PASSWORD': os.environ['DEFAULT_DBPASS'],
        'HOST': os.environ['DEFAULT_DBHOST'],
        'OPTIONS': {
            'driver': os.environ['DEFAULT_DRIVER']
        }
    },
    'public_data': {
        'ENGINE': os.environ['EXTERNAL_DBENGINE'],
        'NAME': os.environ['EXTERNAL_DBNAME'],
         'USER': os.environ['EXTERNAL_DBUSER'],
        'PASSWORD': os.environ['EXTERNAL_DBPASS'],
        'HOST': os.environ['EXTERNAL_DBHOST'],
        'OPTIONS': {
            'driver': os.environ['EXTERNAL_DRIVER']
        }
    },
    'student_profile': {
        'ENGINE': os.environ['STUDENT_DBENGINE'],
        'NAME': os.environ['STUDENT_DBNAME'],
        ' USER': os.environ['STUDENT_DBUSER'],
        'PASSWORD': os.environ['STUDENT_DBPASS'],
        'HOST': os.environ['STUDENT_DBHOST'],
        'OPTIONS': {
            'driver': os.environ['STUDENT_DRIVER']
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

## this COOKIE SETTING IS TO SET COOKIE TO BE both HTTPONLY AND SECURE
#SESSION_COOKIE_PATH = '/;HttpOnly'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

GRAPHENE = {
    'SCHEMA': 'api.graphqlapi.schema.schema',
    ## Have been commented,https://github.com/howtographql/howtographql/issues/983
    #'MIDDLEWARE': [
    #    'graphql_jwt.middleware.JSONWebTokenMiddleware',
    #],
}



#authentication Location
AUTH_USER_MODEL = "access_control.User"


AUTHENTICATION_BACKENDS = (
    'access_control.EntityGroupBackend.ModelBackend',
    'django.contrib.auth.backends.ModelBackend', # this is default
)

STATICFILES_DIRS = [
     os.path.join(BASE_DIR, 'profile_images'),
 ]

STATICFILES_STORAGE = 'storages.backends.azure_storage.AzureStorage'
DEFAULT_FILE_STORAGE = 'data_science_portal_api.custom_azure.AzureMediaStorage'

AZURE_ACCOUNT_NAME = 'devportalaps'
AZURE_ACCOUNT_KEY = 'Z2kB3mV+aIz+6F5pghdaOUxWaToxkFkSqn92119SRJl8xwUp2xq+iJYGE1hBpVsKwMAGa7R+bUR0ymqKoavvfw=='
STATIC_LOCATION = '$web'
AZURE_LOCATION = '$web'
AZURE_CONTAINER = '$web'

AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
